In [6]:
import requests
import pandas as pd
import json
r = requests.get("https://api.hh.ru/vacancies?text=data scientist")
df = pd.DataFrame(r.json())

In [9]:
df.to_json('hh.json')

In [10]:
parsed = json.loads('hh.json')
json.dumps(parsed, indent=4)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [24]:
pd.DataFrame(r.json()['items'])

,id,premium,name,department,has_test,response_letter_required,area,salary,type,address,...,alternate_url,relations,employer,snippet,contacts,schedule,working_days,working_time_intervals,working_time_modes,accept_temporary
0,42813933,False,Data Scientist (компьютерное зрение),None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 70000, 'to': 400000, 'currency': 'RUR...","{'id': 'open', 'name': 'Открытая'}",None,...,https://hh.ru/vacancy/42813933,[],"{'id': '1980636', 'name': 'Дип Системс', 'url'...",{'requirement': 'Опыт успешного применение Dee...,None,"{'id': 'remote', 'name': 'Удаленная работа'}",[],[],[],True
1,42277725,False,Data Scientist (аналитик данных в области упра...,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 60000, 'to': 150000, 'currency': 'RUR...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Москва', 'street': 'Новодмитровская ...",...,https://hh.ru/vacancy/42277725,[],"{'id': '779', 'name': 'ЭКОПСИ Консалтинг', 'ur...",{'requirement': 'У Вас есть высшее образование...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
2,42844649,False,Data Scientist,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 60000, 'to': 200000, 'currency': 'RUR...","{'id': 'open', 'name': 'Открытая'}",None,...,https://hh.ru/vacancy/42844649,[],"{'id': '4948337', 'name': 'Артистраж', 'url': ...",{'requirement': 'Опыт работы от 1 года. Python...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
3,42891788,False,Младший аналитик / Data Scientist Junior,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,"{'id': 'open', 'name': 'Открытая'}","{'city': 'Москва', 'street': 'Самотёчная улица...",...,https://hh.ru/vacancy/42891788,[],"{'id': '863273', 'name': 'MillionAgents', 'url...","{'requirement': 'Python: опыт работы с Pandas,...",None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
4,42683816,False,Data Scientist,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 180000, 'to': 250000, 'currency': 'RU...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Москва', 'street': '5-я Магистральна...",...,https://hh.ru/vacancy/42683816,[],"{'id': '146328', 'name': 'Максконсалт', 'url':...",{'requirement': 'Практический опыт работы с Sc...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],"[{'id': 'from_four_to_six_hours_in_a_day', 'na...",[],True
5,41827452,True,Аналитик данных (Data scientist),None,False,False,"{'id': '2', 'name': 'Санкт-Петербург', 'url': ...","{'from': 90000, 'to': None, 'currency': 'RUR',...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Санкт-Петербург', 'street': 'улица Е...",...,https://hh.ru/vacancy/41827452,[],"{'id': '2633363', 'name': 'Финансово-правовой ...",{'requirement': 'Уверенное владение Python (в ...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
6,42782002,False,Data Scientist / Аналитик,None,False,False,"{'id': '2', 'name': 'Санкт-Петербург', 'url': ...","{'from': 150000, 'to': 200000, 'currency': 'RU...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Санкт-Петербург', 'street': 'Чкаловс...",...,https://hh.ru/vacancy/42782002,[],"{'id': '4295296', 'name': 'Софтвайс', 'url': '...",{'requirement': 'Опыт работы с Big <highlightt...,None,"{'id': 'flexible', 'name': 'Гибкий график'}",[],[],[],False
7,42832748,False,Data Scientist,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 120000, 'to': 180000, 'currency': 'RU...","{'id': 'open', 'name': 'Открытая'}",None,...,https://hh.ru/vacancy/42832748,[],"{'id': '4382297', 'name': 'МАГ Девелопмент', '...",{'requirement': 'Опыт работы в <highlighttext>...,None,"{'id': 'remote', 'name': 'Удаленная работа'}",[],[],[],False
8,39912622,False,Data Scientist / Quantitative Researcher,None,False,True,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 250000, 'to': None, 'currency': 'RUR'...","{'id': 'open', 'name': 'Открытая'}","{'city': None, 'street': None, 'building': Non...",...,https://hh.ru/vacancy/39912622,[],"{'id': '1085810', 'name': 'Знаменка Капитал', ...",{'requirement': 'Хорошая академическая подгото...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
9,42880923,False,Data scientist,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,"{'id': 'open', 'name': 'Открытая'}","{'city': 'Москва', 'street': 'улица Петровка',...",...,https://hh.ru/vacancy/42880923,[],"{'id': '766468', 'name': 'Группа компаний С7',...",{'requirement': 'Имеете 2+ лет опыта работы с ...,None,"{'id': 'flexible', 'name': 'Гибкий график'}",[],[],[],False
10,42783985,False,Junior Data Scientist,"{'id': '662769-662769-minsk', 'name': 'Wargami...",False,False,"{'id': '1002', 'name': 'Минск', 'url': 'https:...",None,"{'id': 'open', 'name': 'Открытая'}",None,...,https://hh.ru/vacancy/42783985,[],"{'id': '662769', 'name': 'Wargaming', 'url': '...",{'requirement': 'Знание и опыт использования к...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
11,42878760,False,Python Developer / ML Engineer,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 5000, 'to': 8000, 'currency': 'USD', ...","{'id': 'open', 'name': 'Открытая'}",None,...,https://hh.ru/vacancy/42878760,[],"{'id': '4456441', 'name': 'Hunt For You', 'url...","{'requirement': 'Опыт ML проектами 5+ лет, опы...",None,"{'id': 'remote', 'name': 'Удаленная работа'}",[],[],[],False
12,42908865,False,Data Scientist инженер (middle/senior),None,False,False,"{'id': '2', 'name': 'Санкт-Петербург', 'url': ...","{'from': 150000, 'to': 300000, 'currency': 'RU...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Санкт-Петербург', 'street': 'площадь...",...,https://hh.ru/vacancy/42908865,[],"{'id': '2283197', 'name': 'Виго Лаб', 'url': '...",{'requirement': 'По мат. моделям и машинному о...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
13,42554963,False,Аналитик данных (Data scientist),None,False,False,"{'id': '66', 'name': 'Нижний Новгород', 'url':...","{'from': 70000, 'to': None, 'currency': 'RUR',...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Нижний Новгород', 'street': 'Ошарска...",...,https://hh.ru/vacancy/42554963,[],"{'id': '1031211', 'name': 'Медиа Страйк', 'url...","{'requirement': 'Подготовка баз данных, присыл...",None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
14,42588736,False,Senior Data Scientist /Quantitative Analyst (К...,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 3500, 'to': 4000, 'currency': 'EUR', ...","{'id': 'open', 'name': 'Открытая'}",None,...,https://hh.ru/vacancy/42588736,[],"{'id': '2776323', 'name': 'Skanestas Investmen...",{'requirement': 'От 3-х лет практического опыт...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
15,42858638,False,Data Scientist,None,False,False,"{'id': '2', 'name': 'Санкт-Петербург', 'url': ...","{'from': None, 'to': 150000, 'currency': 'RUR'...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Санкт-Петербург', 'street': 'Невский...",...,https://hh.ru/vacancy/42858638,[],"{'id': '104085', 'name': 'Многопрофильная клин...",{'requirement': 'Опыт работы с BI (Tableau / Q...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
16,42766574,False,Senior Data Scientist,None,False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...","{'from': 100000, 'to': 200000, 'currency': 'RU...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Екатеринбург', 'street': 'улица Малы...",...,https://hh.ru/vacancy/42766574,[],"{'id': '776314', 'name': 'Парфюмерный супермар...",{'requirement': '...из внешних источников. Зна...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
17,42916116,False,Junior Data Scientist (SberDevices),"{'id': '3529-3529-it', 'name': 'Сбер. IT'}",False,False,"{'id': '1', 'name': 'Москва', 'url': 'https://...",None,"{'id': 'open', 'name': 'Открытая'}","{'city': 'Москва', 'street': 'Кутузовский прос...",...,https://hh.ru/vacancy/42916116,[],"{'id': '3529', 'name': 'Сбербанк', 'url': 'htt...",{'requirement': 'Опыт работы с большими объема...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False
18,41953984,False,Data Scientist,None,False,False,"{'id': '90', 'name': 'Томск', 'url': 'https://...","{'from': 120000, 'to': 180000, 'currency': 'RU...","{'id': 'open', 'name': 'Открытая'}",None,...,https://hh.ru/vacancy/41953984,[],"{'id': '4382297', 'name': 'МАГ Девелопмент', '...",{'requirement': 'Опыт работы в <highlighttext>...,None,"{'id': 'remote', 'name': 'Удаленная работа'}",[],[],[],False
19,42868724,False,Data Scientist | Junior,None,False,False,"{'id': '90', 'name': 'Томск', 'url': 'https://...","{'from': 40000, 'to': 70000, 'currency': 'RUR'...","{'id': 'open', 'name': 'Открытая'}","{'city': 'Томск', 'street': 'микрорайон Академ...",...,https://hh.ru/vacancy/42868724,[],"{'id': '1178085', 'name': 'ENBISYS', 'url': 'h...",{'requirement': 'Аналитический склад ума. Вним...,None,"{'id': 'fullDay', 'name': 'Полный день'}",[],[],[],False

In [23]:
pd.DataFrame(r.json()['items'])['url']

0     https://api.hh.ru/vacancies/42813933?host=hh.ru
1     https://api.hh.ru/vacancies/42277725?host=hh.ru
2     https://api.hh.ru/vacancies/42844649?host=hh.ru
3     https://api.hh.ru/vacancies/42891788?host=hh.ru
4     https://api.hh.ru/vacancies/42683816?host=hh.ru
5     https://api.hh.ru/vacancies/41827452?host=hh.ru
6     https://api.hh.ru/vacancies/42782002?host=hh.ru
7     https://api.hh.ru/vacancies/42832748?host=hh.ru
8     https://api.hh.ru/vacancies/39912622?host=hh.ru
9     https://api.hh.ru/vacancies/42880923?host=hh.ru
10    https://api.hh.ru/vacancies/42783985?host=hh.ru
11    https://api.hh.ru/vacancies/42878760?host=hh.ru
12    https://api.hh.ru/vacancies/42908865?host=hh.ru
13    https://api.hh.ru/vacancies/42554963?host=hh.ru
14    https://api.hh.ru/vacancies/42588736?host=hh.ru
15    https://api.hh.ru/vacancies/42858638?host=hh.ru
16    https://api.hh.ru/vacancies/42766574?host=hh.ru
17    https://api.hh.ru/vacancies/42916116?host=hh.ru
18    https://api.hh.ru/vacancies/41953984?host=hh.ru
19    https://api.hh.ru/vacancies/42868724?host=hh.ru
Name: url, dtype: object

In [20]:
pd.DataFrame(r.json()['items']).columns

Index(['id', 'premium', 'name', 'department', 'has_test',
       'response_letter_required', 'area', 'salary', 'type', 'address',
       'response_url', 'sort_point_distance', 'published_at', 'created_at',
       'archived', 'apply_alternate_url', 'insider_interview', 'url',
       'alternate_url', 'relations', 'employer', 'snippet', 'contacts',
       'schedule', 'working_days', 'working_time_intervals',
       'working_time_modes', 'accept_temporary'],
      dtype='object')